//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmaEnlace.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FarmaEnlace.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid Birthday date..
        /// </summary>
        public static string BirthDayValidation {
            get {
                return ResourceManager.GetString("BirthDayValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Phone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CellPhone.
        /// </summary>
        public static string CellPhoneValidation {
            get {
                return ResourceManager.GetString("CellPhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string ChooseOption {
            get {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the Day of birth.
        /// </summary>
        public static string DayValidation {
            get {
                return ResourceManager.GetString("DayValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email could not be sent..
        /// </summary>
        public static string EmailErrorSent {
            get {
                return ResourceManager.GetString("EmailErrorSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your cell phone.
        /// </summary>
        public static string EnterCellPhone {
            get {
                return ResourceManager.GetString("EnterCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your identification.
        /// </summary>
        public static string EnterID {
            get {
                return ResourceManager.GetString("EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, there is not an active internet connection..
        /// </summary>
        public static string ErrorConection {
            get {
                return ResourceManager.GetString("ErrorConection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, the Location service has been denied for this app. If you want to use its features you have to go to your phone settings and enable or reset this permissions..
        /// </summary>
        public static string ErrorGPSDenied {
            get {
                return ResourceManager.GetString("ErrorGPSDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, please try again..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location could not be establish. Please try again..
        /// </summary>
        public static string ErrorNoGPS {
            get {
                return ResourceManager.GetString("ErrorNoGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, the location service is not available..
        /// </summary>
        public static string ErrorNoGPSAvaible {
            get {
                return ResourceManager.GetString("ErrorNoGPSAvaible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is not available, please try latter..
        /// </summary>
        public static string ErrorService {
            get {
                return ResourceManager.GetString("ErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string ErrorUserNotExist {
            get {
                return ResourceManager.GetString("ErrorUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmaEnlace.
        /// </summary>
        public static string FarmaEnlace {
            get {
                return ResourceManager.GetString("FarmaEnlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Us.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated code.
        /// </summary>
        public static string GeneratedCode {
            get {
                return ResourceManager.GetString("GeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your identification type.
        /// </summary>
        public static string IdentificationTypeValidation {
            get {
                return ResourceManager.GetString("IdentificationTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your identification.
        /// </summary>
        public static string IdentificationValidation {
            get {
                return ResourceManager.GetString("IdentificationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Type.
        /// </summary>
        public static string IdType {
            get {
                return ResourceManager.GetString("IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        public static string IDValidation {
            get {
                return ResourceManager.GetString("IDValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Promotion.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid birth month..
        /// </summary>
        public static string MonthValidation {
            get {
                return ResourceManager.GetString("MonthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby Pharmacies.
        /// </summary>
        public static string NearbyPharmacies {
            get {
                return ResourceManager.GetString("NearbyPharmacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation, does not match..
        /// </summary>
        public static string NewPasswordConfirmNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordConfirmNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be 4 numeric characters length..
        /// </summary>
        public static string NewPasswordLengthValidation {
            get {
                return ResourceManager.GetString("NewPasswordLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password..
        /// </summary>
        public static string NewPasswordValidation {
            get {
                return ResourceManager.GetString("NewPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information.
        /// </summary>
        public static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no product stock.
        /// </summary>
        public static string NoProductStock {
            get {
                return ResourceManager.GetString("NoProductStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid passport.
        /// </summary>
        public static string PasaportValidation {
            get {
                return ResourceManager.GetString("PasaportValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *********.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change was successful.
        /// </summary>
        public static string PasswordChangeSuccessful {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password confirm..
        /// </summary>
        public static string PasswordConfirmValidation {
            get {
                return ResourceManager.GetString("PasswordConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is not valid..
        /// </summary>
        public static string PasswordCurrentValidation {
            get {
                return ResourceManager.GetString("PasswordCurrentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was sent to your email!.
        /// </summary>
        public static string PasswordSentEmail {
            get {
                return ResourceManager.GetString("PasswordSentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the password..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT.
        /// </summary>
        public static string PharmaciesOnDuty {
            get {
                return ResourceManager.GetString("PharmaciesOnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Finder.
        /// </summary>
        public static string PharmacyFinder {
            get {
                return ResourceManager.GetString("PharmacyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Catalog.
        /// </summary>
        public static string ProductCatalog {
            get {
                return ResourceManager.GetString("ProductCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activated.
        /// </summary>
        public static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result: {0}.
        /// </summary>
        public static string ResultSearch {
            get {
                return ResourceManager.GetString("ResultSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ruc.
        /// </summary>
        public static string RucValidation {
            get {
                return ResourceManager.GetString("RucValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find stock.
        /// </summary>
        public static string SearchStock {
            get {
                return ResourceManager.GetString("SearchStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See list.
        /// </summary>
        public static string SeeList {
            get {
                return ResourceManager.GetString("SeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Map.
        /// </summary>
        public static string ShowOnMap {
            get {
                return ResourceManager.GetString("ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your code has expired,  try again..
        /// </summary>
        public static string TimeElapsedCode {
            get {
                return ResourceManager.GetString("TimeElapsedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear user, please try again..
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 Hours Pharmacies.
        /// </summary>
        public static string TwentyFourHoursPharmacies {
            get {
                return ResourceManager.GetString("TwentyFourHoursPharmacies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Card.
        /// </summary>
        public static string VirtualCard {
            get {
                return ResourceManager.GetString("VirtualCard", resourceCulture);
            }
        }
    }
}
